apiVersion: v1
kind: Secret
metadata:
  name: spa-keycloak-secret
  namespace: {{ .Release.namespace }}
type: Opaque
stringData:
  KEYCLOAK_ISSUER_URI: {{ .Values.keycloak.issuerUri | quote }}
  KEYCLOAK_JWKS_URI: "http://host.docker.internal:18081/realms/spa-booking/protocol/openid-connect/certs"

